---
- name: Clean up test results for groupadd testing 
  hosts: rootdc
  vars_files:
    - vars/main.yml
    - vars/ad_creds.yml
  tasks:
    - name: Remove Root_Test_Group
      community.windows.win_domain_group:
        domain_username: "{{ domain_username }}"
        domain_password: "{{ domain_password }}"
        domain_server: "{{ root_domain_server }}"
        name: "{{ Root_Test_Group_DN }}"
        state: absent